TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sfi.Sfi': TRUE
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'print'
          title: 'Print'
          position: 200
      navigateComponent:
        nodeTree:
          loadingDepth: 1
#          presets:
#            default:
#              baseNodeType: 'TYPO3.Neos:Document,!Sfi.News:News'
    nodeTypes:
      groups:
        contentBlocks:
          position: 110
          label: 'Content Blocks'
  # TYPO3CR:
  #   contentDimensions:
  #   # Content dimension "language" serves for translation of content into different languages. Its value specifies
  #   # the language or language variant by means of a locale.
  #     'language':
  #       # The default dimension that is applied when creating nodes without specifying a dimension
  #       default: 'ru'
  #       # The default preset to use if no URI segment was given when resolving languages in the router
  #       defaultPreset: 'ru'
  #       label: 'Language'
  #       icon: 'icon-language'
  #       presets:
  #         'ru':
  #           label: 'Russian'
  #           values: ['ru']
  #           uriSegment: 'ru'
  #         'en':
  #           label: 'English'
  #           values: ['en']
  #           uriSegment: 'en'

Sfi:
  Sfi:
    viewHelpers:
      partialRootPath: 'resource://Sfi.Sfi/Private/Partials/'

